name: Reusable workflow for CI/CD

on:
  workflow_call:
    inputs:
      environment-name:
        type: string
        required: true
      webapp-name:
        type: string
        required: true

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  RELEASE_ZIP_NAME: 'release.zip'

jobs:
  build:
    name: Build
    runs-on: self-hosted
    environment: ${{ inputs.environment-name }}
    steps:        
      - uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build solution
        run: |
          dotnet restore ./CodeAcademy
          dotnet build ./CodeAcademy
      
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Create Publish Folder
        run: dotnet publish ./CodeAcademy -c Release --property PublishDir="../myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app-${{ inputs.environment-name }}
          path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp    


  deploy:
    runs-on: self-hosted
    needs: build
    environment:
      name: ${{ inputs.environment-name }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}/swagger/index.html

    steps:
      # On the self hosted runners we need to clean up old build files before new build (not relevant for normal Github Actions action)
      - name: Cleanup previous runs (only on self-hosted)
        if: runner.environment == 'self-hosted'
        run: rm -rf /home/runner/actions-runner/_work/*
        
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app-${{ inputs.environment-name }}
        env: # This isnt needed when running in Githubs own runners, but needs to be specified if running on self hosted runners
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ inputs.webapp-name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
