name: Terraform Plan and Apply

on:
  push:
    branches: [main]
    paths:
      - '**/terraform/**'
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**/terraform/**'
  workflow_dispatch:

#on:
#  push:
#    branches:
#      - main
#    paths:
#      - '**/terraform/**'  
#  pull_request:
#    branches:
#      - main
#    paths:
#      - '**/terraform/**'
#  workflow_dispatch:

#Special permissions required for OIDC authentication
permissions:
  contents: read
  pull-requests: write
    
jobs:
  terraform-plan-apply-test:
    name: "Test"
    uses: "Sopra-Steria-Code-Academy/Samling-1-Templates/.github/workflows/terraform-plan-apply-template.yml@main"
    with:
      environment-name: 'test'
    secrets:
      client-id: ${{ secrets.TF_AZURE_CLIENT_ID }}
      subscription-id: ${{ secrets.TF_AZURE_SUBSCRIPTION_ID }}
      tenant-id: ${{ secrets.TF_AZURE_TENANT_ID }}
      client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
